# Generated by Django 5.0.6 on 2024-05-10 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ideaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=50)),
                ('businessLocation', models.CharField(max_length=30)),
                ('businessType', models.CharField(max_length=50)),
                ('investmentAmount', models.PositiveBigIntegerField()),
                ('contractDuration', models.PositiveIntegerField()),
                ('numberOfPeople', models.PositiveIntegerField()),
                ('businessDescription', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
